# first step parameters
input_filepath: C:\Users\Administrator\GitHub\nlp-paper-implementation\glove\data\demo_data.pkl 
vocab_size: 100000
window_size: 10
## the number of paritions to divide cooccurence matrix in 
num_partitions: 10
## h5py parameters
chunk_size: 1000000

# when used in first step, specify the output directory of cooccurrence entries
# when used in second step, specify where to read cooccurrence entries from
cooccurrence_dir: C:\Users\Administrator\GitHub\nlp-paper-implementation\glove\data

# second step parameters
output_filepath: C:\Users\Administrator\GitHub\nlp-paper-implementation\glove\data\model.pt
## training parameters
batch_size: 32
num_epochs: 20
device: cpu
learning_rate: 0.05
## glove paremeters
embedding_size: 100
x_max: 100
alpha: 0.75
